import './globals.css';
import 'react-toastify/dist/ReactToastify.css';

import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import React from 'react';
import { ToastContainer } from 'react-toastify';

import { Providers } from '@/components/providers';

const roboto = Roboto({
    weight: ['300', '400', '500', '700'],
    subsets: ['latin'],
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'GitQuasar',
    description: 'Generated by create next app',
};

const RootLayout = async ({
    children,
    params: { locale },
}: Readonly<{
    children: React.ReactNode;
    params: {
        locale: string;
    };
}>) => {
    const messages = await getMessages();

    return (
        <html lang={locale}>
            <body className={roboto.className}>
                <NextIntlClientProvider messages={messages}>
                    <Providers>{children}</Providers>
                </NextIntlClientProvider>
                <ToastContainer />
            </body>
        </html>
    );
};

export default RootLayout;
